{
    "version": "1.0.0",
    "title": "System is resilient to provider's failures",
    "description": "Can our consumer survive gracefully a provider's failure?",
    "tags": [
        "service",
        "kubernetes",
        "quarkus"
    ],
    "steady-state-hypothesis": {
        "title": "Services are all available and healthy",
        "probes": [
            {
                "type": "probe",
                "name": "all-services-are-healthy",
                "tolerance": true,
                "provider": {
                    "type": "python",
                    "module": "chaosk8s.probes",
                    "func": "all_microservices_healthy"
                }
            },
            {
                "type": "probe",
                "name": "consumer-service-must-still-respond",
                "tolerance": 200,
                "provider": {
                    "type": "http",
                    "url": "http://192.168.64.39:32568/hello"
                }
            }
        ]
    },
    "method": [
        {
            "type": "action",
            "name": "stop-provider-service",
            "provider": {
                "type": "process",
                "path": "kubectl",
                "timeout": 60,
                "arguments": {
                    "delete": "",
                    "-f": "provider-deployment.json"
                }
            },
            "pauses": {
                "after": 15
            }
        },
        {
            "type": "probe",
            "ref": "all-services-are-healthy"
        }
    ],
    "rollbacks": [
        {
            "type": "action",
            "name": "redeploy-service",
            "provider": {
                "type": "process",
                "path": "kubectl",
                "timeout": 60,
                "arguments": {
                    "create": "",
                    "-f": "provider-deployment.json"
                }
            }
        }
    ]
}